version: '3.9'
services:
  web:
    build: .
    container_name: coolify_web
    command: daphne -b 0.0.0.0 -p 8000 matchmaker.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_SETTINGS_MODULE=matchmaker.settings
    env_file:
      - .env
    networks:
      - appnet

  db:
    image: postgres:16
    container_name: coolify_db
    restart: always
    environment:
      POSTGRES_DB: coolifydb
      POSTGRES_USER: coolifyuser
      POSTGRES_PASSWORD: coolifypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  nginx:
    image: nginx:1.25
    container_name: coolify_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local


