version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: matchmaker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - matchmaker_network

  web:
    build: .
    container_name: matchmaker_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
    networks:
      - matchmaker_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py loaddata main/fixtures/initial_data.json &&
             daphne -b 0.0.0.0 -p 8000 matchmaker.asgi:application"

  # Nginx для production (опционально)
  nginx:
    image: nginx:alpine
    container_name: matchmaker_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    depends_on:
      - web
    networks:
      - matchmaker_network
    profiles:
      - production

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  matchmaker_network:
    driver: bridge
